### ISSUE TITLE
missing `set_documentation_group ` missing from Gradio Client

### ISSUE THREAD

**Issue by radames** [pngwn/gradio-imageslider#12]
Trying to run it with `Gradio=4.17.0` and `gradio-imageslider=0.0.18` got `set_documentation_group` missing from Gradio Client

````
python app.py                 
Traceback (most recent call last):
  File "/home/radames/Development/jupyter/app.py", line 2, in <module>
    from gradio_imageslider import ImageSlider
  File "/home/radames/Development/jupyter/venv/lib/python3.10/site-packages/gradio_imageslider/__init__.py", line 1, in <module>
    from .imageslider import ImageSlider
  File "/home/radames/Development/jupyter/venv/lib/python3.10/site-packages/gradio_imageslider/imageslider.py", line 10, in <module>
    from gradio_client.documentation import document, set_documentation_group
ImportError: cannot import name 'set_documentation_group' from 'gradio_client.documentation' (/home/radames/Development/jupyter/venv/lib/python3.10/site-packages/gradio_client/documentation.py)
````

**Comment by pngwn** [comment]
This was a regression that was introduced in 4.17.0 and it fixes in the latest version (4.18.0 - https://pypi.org/project/gradio/). 

I leave this open though as I can fix this on my end as well. 

Thanks for the report!
