### ISSUE TITLE
Some conflict when using in Automatic1111

### ISSUE THREAD

**Issue by sebaxakerhtc** [pngwn/gradio-imageslider#16]
```
*** Error loading script: iface.py
    Traceback (most recent call last):
      File "D:\stable-diffusion-webui\modules\scripts.py", line 527, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\stable-diffusion-webui\extensions\sd-webui-demofusion\scripts\iface.py", line 14, in <module>
        from gradio_imageslider import ImageSlider
      File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio_imageslider\__init__.py", line 1, in <module>
        from .imageslider import ImageSlider
      File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio_imageslider\imageslider.py", line 16, in <module>
        from gradio.events import Events
    ImportError: cannot import name 'Events' from 'gradio.events' (D:\stable-diffusion-webui\venv\lib\site-packages\gradio\events.py)
```

Have tried reinstalling Automatic1111, but the result is the same
gradio 3.41.2

**Comment by pngwn** [comment]
I think this is because the StableDiffusionWebUI is not on gradio 4.0 and does not contain the necessary exports.
