### ISSUE TITLE
TypeError in the console

### ISSUE THREAD

**Issue by toshas** [pngwn/gradio-imageslider#7]
Hi @pngwn, thanks for the great package! I noticed that demos with the slider component have the following error in the browser console:

```
Toast.svelte:8 TypeError: ((intermediate value) || (intermediate value)) is not a function
    at load_component (Toast.svelte:8:27)
    at Blocks.svelte:284:15
    at Array.forEach (<anonymous>)
    at prepare_components (Blocks.svelte:228:14)
    at $$self.$$.update (Blocks.svelte:157:25)
    at init (svelte.js:3246:5)
    at new Blocks (Blocks.svelte:669:31)
    at Array.create_if_block_1 (Index.svelte:416:26)
    at Object.p (Index.svelte:365:102)
    at update_slot_base (svelte.js:203:8)
```

Checked with these two spaces, seems reproducible with Chrome on OSX: 
- https://huggingface.co/spaces/toshas/marigold
- https://huggingface.co/spaces/radames/Enhance-This-DemoFusion-SDXL

**Comment by pngwn** [comment]
This is actually an issue with gradio core, when using custom components. I'll fix it over there!

Thanks for the report!

**Comment by pngwn** [comment]
I'll move this issue across to the gradio repo!

**Comment by pngwn** [comment]
https://github.com/gradio-app/gradio/issues/6909

**Comment by pngwn** [comment]
fixed now!
